# environment

domain: mujoco
env: hopper-medium-replay-v2
fake_label: false
modality: 'state'  # state/pixel
structure: 'mlp' # mlp/transformer1/transformer2/transformer3
clip_action: 0.999  # only d4rl
stack: false  # stack frame in pixel benchmark, only atari

# learning
ensemble_size: 3
batch_size: 64
n_epochs: 50
num_query: 2000s
len_query: 200
data_dir: ../crowdsource_human_labels

# misc
seed: 999
exp_name: CS-MLP
save_model: true
use_wandb: false
wandb_project: Uni-RLHF
wandb_entity: xiguapi

# transformer structure
d_model: 256
nhead: 4
num_layers: 1
max_seq_len: 200

# robosuite
reward_model_path: $your_model_path
pkl_path: $your_pkl_path